### ISSUE TITLE
Issues query response always empty

### ISSUE THREAD

**Issue by schlapzz** [grafana/github-datasource#144] opened 2021-09-29 07:05 UTC
The GitHub datasource is working for the Pull Requests stats. But when I'm trying to query the number of (open) issues, I always get a empty response, even if there are open and closed Issues. The stats for the pull requests are correct.

For example I try to query this repository
![image](https://user-images.githubusercontent.com/69156773/135219340-b7c2c372-5e8b-4711-a305-5e6c7d8e6071.png)

I never get any data for the issues.

**Comment by SylivanKenobi** [comment] 2022-03-01 08:56
The Issue is still there. Can someone help?

**Comment by cletter7** [comment] 2023-01-26 09:29
Cannot reproduce the issue. Please pay attention to the "Time Field", maybe there are not issues created in the selected time range. Try to choose another value for the Time Field.

https://user-images.githubusercontent.com/1436174/214801539-99b76f6f-98bf-4dde-b91f-ceb907b3a231.mov

Closing the issue. Feel free to reopen with describing steps to reproduce.

**Closed by cletter7** 2023-01-26 09:29 UTC
Labels: bug
