### ISSUE TITLE
Graph on Commits not working

### ISSUE THREAD

**Issue by cilerler** [grafana/github-datasource#133] opened 2021-05-26 19:13 UTC
I can get the results in the Table for commits but not with Graph.  And I would like to be able to graph it based on `committed_at`

![image](https://user-images.githubusercontent.com/385958/119717633-8bebdf00-be34-11eb-92aa-51e95cb64afe.png)

![image](https://user-images.githubusercontent.com/385958/119717696-a02fdc00-be34-11eb-94f7-a348e5033142.png)

**Comment by kminehart** [comment] 2021-05-26 19:53
Closing this as it's a duplicate of https://github.com/grafana/github-datasource/issues/62

Feel free to read that discussion and provide your input!

**Closed by kminehart** 2021-05-26 19:53 UTC
