### ISSUE TITLE
Showing commit data as graph, nor table

### ISSUE THREAD

**Issue by Fufe1ok** [grafana/github-datasource#92] opened 2020-10-30 12:29 UTC
Is it possible to show commit data as graph, not in table format?

**Comment by kminehart** [comment] 2020-11-27 14:37
Sorry, completely missed this.

The short answer is not easily. There's information in the README about this, as well as another open issue https://github.com/grafana/github-datasource/issues/62

**Comment by kminehart** [comment] 2020-11-27 14:37
duplicate of #62

**Closed by kminehart** 2020-11-27 14:37 UTC
Labels: enhancement
