### ISSUE TITLE
Support arm architecture

### ISSUE THREAD

**Issue by aziz** [grafana/github-datasource#93] opened 2020-11-27 07:35 UTC
I'm running a Grafana instance on a raspberry pie and I need the arm architecture of this plugin.

**Comment by fuomag9** [comment] 2021-01-02 19:46
+1 on this, any ETA on ARM32/64 support?

**Comment by kminehart** [comment] 2021-01-14 15:12
hmm. I'll look into it. It can certainly be compiled with ARM support since it's Go. I think we need to just add that to the CI file and auto release it.

**Comment by philosowaffle** [comment] 2021-05-29 13:23
Just checking in to see if there are any updates on this.  Would be great to make this datasource available to those of us running Grafana on raspberry pi's.

**Comment by kminehart** [comment] 2021-05-31 16:27
There are ARM64 versions available in the most recent release

https://github.com/grafana/github-datasource/releases/tag/v1.0.11

**Comment by philosowaffle** [comment] 2021-05-31 17:03
Cool, seems like this issue can be marked as resolved then.

**Comment by philosowaffle** [comment] 2021-05-31 17:07
Note: while the release seems to have ARM64 builds, when trying to install on RaspberryPi v4 Grafana Docker container via following command:

```
grafana-cli plugins install grafana-github-datasource
```

I get the following message:

```
Error: ✗ plugin is not supported on your architecture and OS
```

Using image: `grafana/grafana`

**Comment by timmeinerzhagen** [comment] 2021-05-31 17:17
The arm version does not seem to be published to the grafana repo but using the version in the GitHub release as "custom" plugin url works for me.

Using cli it should work as described [in the grafana docs](https://grafana.com/docs/grafana/latest/administration/cli/#override-default-plugin-zip-url)
`grafana-cli --insecure --pluginUrl https://github.com/grafana/github-datasource/releases/download/v1.0.11/grafana-github-datasource-1.0.11.linux_arm64.zip plugins install grafana-github-datasource`

**Comment by timmeinerzhagen** [comment] 2021-05-31 17:25
The arm builds do not seem to be pushed to the grafana repo but using the GitHub release version as "custom" plugin works for me.

`grafana-cli --pluginUrl https://github.com/grafana/github-datasource/releases/download/v1.0.11/grafana-github-datasource-1.0.11.linux_arm64.zip plugins install grafana-github-datasource`

**Comment by philosowaffle** [comment] 2021-05-31 17:26
Confirmed this works, datasource is added and am able to query for data. Thank you!

**Comment by kminehart** [comment] 2021-05-31 21:00
ah that makes sense. I don't mess with our plugin publishing process at all so I'll have to get someone to help me maybe. I appreciate the command you included to help others get it installed!

**Comment by zoltanbedi** [comment] 2023-03-09 08:17
This is already supported.

**Closed by zoltanbedi** 2023-03-09 08:17 UTC
