### ISSUE TITLE
Importing a Default Github Dashboard yields error message

### ISSUE THREAD

**Issue by lukasztyrala** [grafana/github-datasource#107] opened 2021-02-09 12:45 UTC
Attempt to `Import` `GitHub Default` dashboard (`Data Sources > GitHub > Dashboards`) yields an error message _Dashboard not found_.

![github-plugin_import-dashboard_error.png](https://images.zenhubusercontent.com/5fd249ad27e827ad238eeffe/c6c78788-b975-49e2-82ce-437299d4bd88)

Environment: Cloud,  Enterprise (Licensed), v7.4.0 (c2203b9859)
Browser: Firefox 85.0.1 (64-bit) (the same for other browsers)
OS: macOS BigSur 11.2 (20D64)

**Comment by cletter7** [comment] 2023-01-26 14:26
Cannot reproduce on v8.4 and v9.3, I believe this is fixed by now.

**Closed by cletter7** 2023-01-26 14:26 UTC
Labels: bug
