### ISSUE TITLE
Filtering issues by "closed_at" returns no results

### ISSUE THREAD

**Issue by kminehart** [grafana/github-datasource#76] opened 2020-09-17 14:31 UTC
Because for some reason they're all showing up as `1754-08-30 16:53:05`

**Comment by jneilliii** [comment] 2020-09-17 17:08
I noticed the same issue of all closed_at dates either being the same exact date or empty.

**Comment by cletter7** [comment] 2023-01-26 14:48
Cannot reproduce anymore, probably fixed by now.

**Closed by cletter7** 2023-01-26 14:48 UTC
Labels: bug
